### PR TITLE
Add and Rearrange engines

### PR DESCRIPTION
**Pull request by kailashchoudhary11**
## What will this Pull Request Affect?

# Any additional information?

### CODE REVIEW

**Review by itskegnh — CHANGES_REQUESTED** [review]
I can see some of the engines out of order still, any chance you could order those by alphabetical?

**Comment by kailashchoudhary11** [comment]
Yeah Sure!

**Comment by ArjunSharda** [comment]
Hi, I can see the title of this PR says "Add and Rearrange engines". Did you add any engines? If so can you tell me them as if I merge them I will have to add them to the changelog.

**Comment by kailashchoudhary11** [comment]
Yes I have added engine for leetcode

**Review by itskegnh — APPROVED** [review]

**Review by ArjunSharda — APPROVED** [review]
LGTM to me! Forgot to approve, will merge in the next update.

**Pull request merged**
