### PR TITLE
#93 Added Search engine for customer querygit add .!

### PR DESCRIPTION
**Pull request by ritishbhardwaj**
## What will this Pull Request Affect?

# Any additional information?

### CODE REVIEW

**Comment by ritishbhardwaj** [comment]
@ArjunSharda 
I really want to know the further updates on this PR. 
I really like to be in contact with you regarding further PRs

**Comment by ArjunSharda** [comment]
Hi,

I think this PR will be denied as 4anime contains pirated anime shows and has NSFW ads. I appreciate your PR, but this will not be accepted.

**Comment by ritishbhardwaj** [comment]
i really appreciate your decision 
i will definitely make some new PR which can be merged,
i use adblockers so i forgot , sorry for that

**Comment by ArjunSharda** [comment]
> i really appreciate your decision 
> 
> i will definitely make some new PR which can be merged,
> 
> i use adblockers so i forgot , sorry for that

No it's alright. I appreciate your efforts though.

**Pull request closed without merging**
