### PR TITLE
added view engine list function 

### PR DESCRIPTION
**Pull request by a-1an**
some widely used engines added

### CODE REVIEW

**Review by devarshishimpi — APPROVED** [review]

**Review by ArjunSharda — APPROVED** [review]
Added to the change log but LGTM for me for v2.1.0! Thank you!

**Comment by a-1an** [comment]
Hi, i see this was removed. Something wrong?  @ArjunSharda

**Comment by ArjunSharda** [comment]
One collaboration team member pointed out its not useful anymore as we are
now using Enums in our code.

**Comment by a-1an** [comment]
oh, may i work on that again? 
I'll code to display from enum class.
@ArjunSharda

**Pull request merged**
